import { Category } from './app.api';

const categories: Category[] = [
  {
    id: '1',
    name: 'Action (set A)',
    preview: '/images/dive.jpg',
    words: [
      {
        id: '1',
        word: 'cry',
        translation: 'плакать',
        image: '/images/cry.jpg',
        audioSrc: '/audio/cry.mp3',
      },
      {
        id: '2',
        word: 'dance',
        translation: 'танцевать',
        image: '/images/dance.jpg',
        audioSrc: '/audio/dance.mp3',
      },
      {
        id: '3',
        word: 'dive',
        translation: 'нырять',
        image: '/images/dive.jpg',
        audioSrc: '/audio/dive.mp3',
      },
      {
        id: '4',
        word: 'draw',
        translation: 'рисовать',
        image: '/images/draw.jpg',
        audioSrc: '/audio/draw.mp3',
      },
      {
        id: '5',
        word: 'fish',
        translation: 'ловить рыбу',
        image: '/images/fish.jpg',
        audioSrc: '/audio/fish.mp3',
      },
      {
        id: '6',
        word: 'fly',
        translation: 'летать',
        image: '/images/fly.jpg',
        audioSrc: '/audio/fly.mp3',
      },
      {
        id: '7',
        word: 'hug',
        translation: 'обнимать',
        image: '/images/hug.jpg',
        audioSrc: '/audio/hug.mp3',
      },
      {
        id: '8',
        word: 'jump',
        translation: 'прыгать',
        image: '/images/jump.jpg',
        audioSrc: '/audio/jump.mp3',
      },
    ],
  },
  {
    id: '2',
    name: 'Action (set B)',
    preview: '/images/run.jpg',
    words: [
      {
        id: '9',
        word: 'open',
        translation: 'открывать',
        image: '/images/open.jpg',
        audioSrc: '/audio/open.mp3',
      },
      {
        id: '10',
        word: 'play',
        translation: 'играть',
        image: '/images/play.jpg',
        audioSrc: '/audio/play.mp3',
      },
      {
        id: '11',
        word: 'point',
        translation: 'указывать',
        image: '/images/point.jpg',
        audioSrc: '/audio/point.mp3',
      },
      {
        id: '12',
        word: 'ride',
        translation: 'ездить',
        image: '/images/ride.jpg',
        audioSrc: '/audio/ride.mp3',
      },
      {
        id: '13',
        word: 'run',
        translation: 'бегать',
        image: '/images/run.jpg',
        audioSrc: '/audio/run.mp3',
      },
      {
        id: '14',
        word: 'sing',
        translation: 'петь',
        image: '/images/sing.jpg',
        audioSrc: '/audio/sing.mp3',
      },
      {
        id: '15',
        word: 'skip',
        translation: 'скакать',
        image: '/images/skip.jpg',
        audioSrc: '/audio/skip.mp3',
      },
      {
        id: '16',
        word: 'swim',
        translation: 'плавать',
        image: '/images/swim.jpg',
        audioSrc: '/audio/swim.mp3',
      },
    ],
  },
  {
    id: '3',
    name: 'Animal (set A)',
    preview: '/images/chick.jpg',
    words: [
      {
        id: '17',
        word: 'cat',
        translation: 'кот',
        image: '/images/cat.jpg',
        audioSrc: '/audio/cat.mp3',
      },
      {
        id: '18',
        word: 'chick',
        translation: 'цыплёнок',
        image: '/images/chick.jpg',
        audioSrc: '/audio/chick.mp3',
      },
      {
        id: '19',
        word: 'chicken',
        translation: 'курица',
        image: '/images/chicken.jpg',
        audioSrc: '/audio/chicken.mp3',
      },
      {
        id: '20',
        word: 'dog',
        translation: 'собака',
        image: '/images/dog.jpg',
        audioSrc: '/audio/dog.mp3',
      },
      {
        id: '21',
        word: 'horse',
        translation: 'лошадь',
        image: '/images/horse.jpg',
        audioSrc: '/audio/horse.mp3',
      },
      {
        id: '22',
        word: 'pig',
        translation: 'свинья',
        image: '/images/pig.jpg',
        audioSrc: '/audio/pig.mp3',
      },
      {
        id: '23',
        word: 'rabbit',
        translation: 'кролик',
        image: '/images/rabbit.jpg',
        audioSrc: '/audio/rabbit.mp3',
      },
      {
        id: '24',
        word: 'sheep',
        translation: 'овца',
        image: '/images/sheep.jpg',
        audioSrc: '/audio/sheep.mp3',
      },
    ],
  },
  {
    id: '4',
    name: 'Animal (set B)',
    preview: '/images/dolphin.jpg',
    words: [
      {
        id: '25',
        word: 'bird',
        translation: 'птица',
        image: '/images/bird.jpg',
        audioSrc: '/audio/bird.mp3',
      },
      {
        id: '26',
        word: 'fish',
        translation: 'рыба',
        image: '/images/fish1.jpg',
        audioSrc: '/audio/fish.mp3',
      },
      {
        id: '27',
        word: 'frog',
        translation: 'жаба',
        image: '/images/frog.jpg',
        audioSrc: '/audio/frog.mp3',
      },
      {
        id: '28',
        word: 'giraffe',
        translation: 'жираф',
        image: '/images/giraffe.jpg',
        audioSrc: '/audio/giraffe.mp3',
      },
      {
        id: '29',
        word: 'lion',
        translation: 'лев',
        image: '/images/lion.jpg',
        audioSrc: '/audio/lion.mp3',
      },
      {
        id: '30',
        word: 'mouse',
        translation: 'мышь',
        image: '/images/mouse.jpg',
        audioSrc: '/audio/mouse.mp3',
      },
      {
        id: '31',
        word: 'turtle',
        translation: 'черепаха',
        image: '/images/turtle.jpg',
        audioSrc: '/audio/turtle.mp3',
      },
      {
        id: '32',
        word: 'dolphin',
        translation: 'дельфин',
        image: '/images/dolphin.jpg',
        audioSrc: '/audio/dolphin.mp3',
      },
    ],
  },
  {
    id: '5',
    name: 'Clothes',
    preview: '/images/boot.jpg',
    words: [
      {
        id: '33',
        word: 'skirt',
        translation: 'юбка',
        image: '/images/skirt.jpg',
        audioSrc: '/audio/skirt.mp3',
      },
      {
        id: '34',
        word: 'pants',
        translation: 'брюки',
        image: '/images/pants.jpg',
        audioSrc: '/audio/pants.mp3',
      },
      {
        id: '35',
        word: 'blouse',
        translation: 'блузка',
        image: '/images/blouse.jpg',
        audioSrc: '/audio/blouse.mp3',
      },
      {
        id: '35',
        word: 'dress',
        translation: 'платье',
        image: '/images/dress.jpg',
        audioSrc: '/audio/dress.mp3',
      },
      {
        id: '37',
        word: 'boot',
        translation: 'ботинок',
        image: '/images/boot.jpg',
        audioSrc: '/audio/boot.mp3',
      },
      {
        id: '38',
        word: 'shirt',
        translation: 'рубашка',
        image: '/images/shirt.jpg',
        audioSrc: '/audio/shirt.mp3',
      },
      {
        id: '39',
        word: 'coat',
        translation: 'пальто',
        image: '/images/coat.jpg',
        audioSrc: '/audio/coat.mp3',
      },
      {
        id: '40',
        word: 'shoe',
        translation: 'туфли',
        image: '/images/shoe.jpg',
        audioSrc: '/audio/shoe.mp3',
      },
    ],
  },
  {
    id: '6',
    name: 'Emotions',
    preview: '/images/happy.jpg',
    words: [
      {
        id: '41',
        word: 'sad',
        translation: 'грустный',
        image: '/images/sad.jpg',
        audioSrc: '/audio/sad.mp3',
      },
      {
        id: '42',
        word: 'angry',
        translation: 'сердитый',
        image: '/images/angry.jpg',
        audioSrc: '/audio/angry.mp3',
      },
      {
        id: '43',
        word: 'happy',
        translation: 'счастливый',
        image: '/images/happy.jpg',
        audioSrc: '/audio/happy.mp3',
      },
      {
        id: '44',
        word: 'tired',
        translation: 'уставший',
        image: '/images/tired.jpg',
        audioSrc: '/audio/tired.mp3',
      },
      {
        id: '45',
        word: 'surprised',
        translation: 'удивлённый',
        image: '/images/surprised.jpg',
        audioSrc: '/audio/surprised.mp3',
      },
      {
        id: '46',
        word: 'scared',
        translation: 'испуганный',
        image: '/images/scared.jpg',
        audioSrc: '/audio/scared.mp3',
      },
      {
        id: '47',
        word: 'smile',
        translation: 'улыбка',
        image: '/images/smile.jpg',
        audioSrc: '/audio/smile.mp3',
      },
      {
        id: '48',
        word: 'laugh',
        translation: 'смех',
        image: '/images/laugh.jpg',
        audioSrc: '/audio/laugh.mp3',
      },
    ],
  },
  {
    id: '7',
    name: 'Fruits',
    preview: '/images/fruits/apple.jpg',
    words: [
      {
        id: '49',
        word: 'apple',
        translation: 'яблоко',
        image: '/images/fruits/apple.jpg',
        audioSrc: '/audio/apple.mp3',
      },
      {
        id: '5',
        word: 'pear',
        translation: 'груша',
        image: '/images/fruits/pear.jpg',
        audioSrc: '/audio/pear.mp3',
      },
      {
        id: '51',
        word: 'avocado',
        translation: 'авокадо',
        image: '/images/fruits/avocado.jpg',
        audioSrc: '/audio/avocado.mp3',
      },
      {
        id: '52',
        word: 'banana',
        translation: 'банан',
        image: '/images/fruits/banana.jpg',
        audioSrc: '/audio/banana.mp3',
      },
      {
        id: '53',
        word: 'grapefruit',
        translation: 'грейпфрут',
        image: '/images/fruits/grapefruit.jpg',
        audioSrc: '/audio/grapefruit.mp3',
      },
      {
        id: '54',
        word: 'mango',
        translation: 'манго',
        image: '/images/fruits/mango.jpg',
        audioSrc: '/audio/mango.mp3',
      },
      {
        id: '55',
        word: 'mandarin',
        translation: 'мандарин',
        image: '/images/fruits/mandarin.jpg',
        audioSrc: '/audio/mandarin.mp3',
      },
      {
        id: '56',
        word: 'orange',
        translation: 'апельсин',
        image: '/images/fruits/orange.jpg',
        audioSrc: '/audio/orange.mp3',
      },
    ],
  },
  {
    id: '8',
    name: 'Vegetables',
    preview: '/images/vegetables/carrot.jpg',
    words: [
      {
        id: '57',
        word: 'carrot',
        translation: 'морковь',
        image: '/images/vegetables/carrot.jpg',
        audioSrc: '/audio/carrot.mp3',
      },
      {
        id: '58',
        word: 'beet',
        translation: 'свёкла',
        image: '/images/vegetables/beet.jpg',
        audioSrc: '/audio/beet.mp3',
      },
      {
        id: '59',
        word: 'cabbage',
        translation: 'капуста',
        image: '/images/vegetables/cabbage.jpg',
        audioSrc: '/audio/cabbage.mp3',
      },
      {
        id: '60',
        word: 'cucumber',
        translation: 'огурец',
        image: '/images/vegetables/cucumber.jpg',
        audioSrc: '/audio/cucumber.mp3',
      },
      {
        id: '61',
        word: 'onion',
        translation: 'лук',
        image: '/images/vegetables/onion.jpg',
        audioSrc: '/audio/onion.mp3',
      },
      {
        id: '62',
        word: 'tomato',
        translation: 'помидор',
        image: '/images/vegetables/tomato.jpg',
        audioSrc: '/audio/tomato.mp3',
      },
      {
        id: '63',
        word: 'potato',
        translation: 'картошка',
        image: '/images/vegetables/potato.jpg',
        audioSrc: '/audio/potato.mp3',
      },
      {
        id: '64',
        word: 'pumpkin',
        translation: 'тыква',
        image: '/images/vegetables/pumpkin.jpg',
        audioSrc: '/audio/pumpkin.mp3',
      },
    ],
  },
];

export default categories;
