export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_MODE = 'TOGGLE_MODE';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_DIFFICULT_WORDS = 'UPDATE_DIFFICULT_WORDS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const START_GAME = 'START_GAME';
export const STOP_GAME = 'STOP_GAME';
export const PLAY_WORD = 'PLAY_WORD';
export const CHOOSE_WORD = 'CHOOSE_WORD';
export const WORD_GUESSED = 'WORD_GUESSED';
export const WORD_NOT_GUESSED = 'WORD_NOT_GUESSED';
export const END_GAME = 'END_GAME';

export const GET_STATISTIC = 'GET_STATISTIC';
export const TRAIN_CLICK = 'TRAIN_CLICK';

export const TOGGLE_LOGIN_POPUP = 'TOGGLE_LOGIN_POPUP';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGOUT = 'LOGOUT';
export const INIT_LOGIN = 'INIT_LOGIN';

export const CREATE_WORD = 'CREATE_CATEGORY';
export const UPDATE_WORD = 'UPDATE_WORD';
export const DELETE_WORD = 'DELETE_WORD';
