export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_MODE = 'TOGGLE_MODE';

export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const UPDATE_DIFFICULT_WORDS = 'UPDATE_DIFFICULT_WORDS';

export const START_GAME = 'START_GAME';
export const STOP_GAME = 'STOP_GAME';
export const PLAY_WORD = 'PLAY_WORD';
export const CHOOSE_WORD = 'CHOOSE_WORD';
export const WORD_GUESSED = 'WORD_GUESSED';
export const WORD_NOT_GUESSED = 'WORD_NOT_GUESSED';
export const END_GAME = 'END_GAME';

export const INIT_STATISTIC = 'INIT_STATISTIC';
export const TRAIN_CLICK = 'TRAIN_CLICK';
export const UPDATE_STATISTIC = 'UPDATE_STATISTIC';
export const RESET_STATISTIC = 'RESET_STATISTIC';
